### ISSUE TITLE
为什么要去除simple模式？

### ISSUE THREAD

**Issue by cnicy** [ant-design/ant-design-pro-cli#10]
为什么要去除simple模式，没搞懂！

**Comment by aihua** [comment]
从代码看ant-design-pro项目的browser-history-simple和simple这两个产生项目模板的分支在github中被删除了。相应地，ant-design-pro-cli代码中移除了simple和browser history simple这两个项目产生选项。
如果需要，可以从版本库中恢复ant-design-pro项目的browser-history-simple和simple这两个分支，只是版本到0.3.x，没有更新到1.0.x。具体原因@sorrycc @luolonghao @lifesinger @tigerlee

**Comment by nikogu** [comment]
统一到标准模式，之后官网可能会提供主题配置，届时可能会有简化版本。
