### ISSUE TITLE
npm run build报错

### ISSUE THREAD

**Issue by shangchuan123** [ant-design/ant-design-pro-cli#123]
fatal - [esbuildHelperChecker] Found conflicts in esbuild helpers: Jt (749.ea5c6f3f.async.js, 980.ed6d7f93.async.js), please set esbuildMinifyIIFE: true in your config file.

**Comment by andyFang94** [comment]
https://github.com/umijs/umi/issues/10959

https://github.com/umijs/umi/issues/10602
