### ISSUE TITLE
uglify failed when building

### ISSUE THREAD

**Issue by zfan40** [ant-design/ant-design-pro-cli#13]
Error Message:
Failed to minify the bundle. Error: index.fdfaf320.js from UglifyJs. Unexpected token: name(staticTag)

npm run start都正常工作

参考了一些网上的资料，不知道靠谱靠谱
https://github.com/webpack/webpack/issues/2972

求指导

**Comment by tuoxiansp** [comment]
同样碰到这个问题，请问怎么解决的呢？
