### ISSUE TITLE
ant-design-pro-cli安装失败

### ISSUE THREAD

**Issue by JasonJie** [ant-design/ant-design-pro-cli#16]
node-pre-gyp ERR! Pre-built binaries not installable for fsevents@1.2.3 and node@10.0.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Hit error EACCES: permission denied, mkdir '/usr/local/lib/node_modules/ant-design-pro-cli/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64' 
gyp ERR! clean error 
gyp ERR! stack Error: EACCES: permission denied, rmdir 'build'
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "clean"
gyp ERR! cwd /usr/local/lib/node_modules/ant-design-pro-cli/node_modules/fsevents
gyp ERR! node -v v10.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/ant-design-pro-cli/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:947:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:236:5)
node-pre-gyp ERR! System Darwin 17.5.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/ant-design-pro-cli/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/ant-design-pro-cli/node_modules/fsevents
node-pre-gyp ERR! node -v v10.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.9.1
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (1)

**Comment by moker-monkey** [comment]
me too.

npm ERR! Unexpected end of JSON input while parsing near '..."commitizen":"^2.8.6"'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mac/.npm/_logs/2018-05-09T09_58_20_708Z-debug.log

**Comment by nikogu** [comment]
用 cnpm

**Comment by 1c7** [comment]
## cnpm work fine
```
cnpm install ant-design-pro-cli -g
```

## Image 1
![image](https://user-images.githubusercontent.com/1804755/42371412-004b520a-8142-11e8-800d-db73554a2cac.png)

## Image 2
![image](https://user-images.githubusercontent.com/1804755/42371421-0d169d0a-8142-11e8-9123-a8d736a9a7b4.png)
