### ISSUE TITLE
为什么pro new在downloading template卡住了不动

### ISSUE THREAD

**Issue by zhanghj819** [ant-design/ant-design-pro-cli#18]
![_20180816210357](https://user-images.githubusercontent.com/1924328/44209872-57cd3500-a197-11e8-9c8d-e8f483316d0c.png)

npm install ant-design-pro-cli -g 删了重新安装，也是一样。请问是否有什么地方？需要删除template，再下载呢？

**Comment by songyang1996** [comment]
遇到了同样的问题 ant design pro直接clone后 start卡在build 10% 
用cli卡在downloading template

**Comment by juemeng** [comment]
也是卡在Auto Installing...不知道下载什么卡住，一直不动

**Comment by PeterChenJian** [comment]
> 遇到了同样的问题 ant design pro直接clone后 start卡在build 10%
> 用cli卡在downloading template

问题解决了吗，我也遇到相同的问题！！！win10 环境

**Comment by mosswang** [comment]
![image](https://user-images.githubusercontent.com/10702492/54471205-6d1f4600-47f0-11e9-8ce0-ea6876c162c7.png)
我也卡在这里，不动了。

**Comment by tiegercs** [comment]
怎么解决的？请说明下，我也遇到同样的问题，谢谢
