### ISSUE TITLE
throw error when src/[models|services] directory does not exist

### ISSUE THREAD

**Issue by weimengxi** [ant-design/ant-design-pro-cli#2]
https://github.com/ant-design/ant-design-pro-cli/blob/a00c32d1e04b0b841e11b99bacfcc5c9d2c527dd/lib/new.js#L209

 在没有使用`pro init` 初始化的新项目下执行 `pro new` 创建 models 或者  services时， 假如项目目录下尚未创建 [models|services] 父目录， 则会抛出 ` ENOENT: no such file or directory` 异常。

是否可以在该行前添加一个判断，假如父目录不存在，就先创建父目录：
```
 fs.ensureDir(`${target}`);
```

补充一下为什么不使用 `pro init`  初始化项目的原因， 从ant-design-pro 中拷贝过来太多内容， 并不完全是我们的项目想用的内容， 一点点删也很麻烦。用  `pro new` 创建需要的模块进行增量式开发是我们目前比较期待的参考方式。

**Comment by weimengxi** [comment]
[Bugfix](https://github.com/ant-design/ant-design-pro-cli/pull/3)

**Comment by nikogu** [comment]
https://github.com/ant-design/ant-design-pro-cli/pull/3
