### ISSUE TITLE
puppeteer 是不是不应该放在dependencies

### ISSUE THREAD

**Issue by xiaohuoni** [ant-design/ant-design-pro-cli#23]
https://github.com/ant-design/ant-design-pro-cli/blob/c6f9437851ebd91e74dc9f0822fa05546cdb0346/package.json#L35

**Comment by xiaohuoni** [comment]
本来puppeteer就很难下，其他不需要测试的，都可以选择不安装它，现在强制绑定到命令里，不安装都不行了。

**Comment by chenshuai2144** [comment]
没有 puppeteer 无法截图的。最好的办法是搞个动态下载 puppeteer

**Comment by xiaohuoni** [comment]
我觉得这些算是pro需要的，并不是在真实项目中，使用pro需要的，还是要分离开比较好。

**Comment by chenshuai2144** [comment]
使用的时候会报错的。
有兴趣搞个 动态下载 puppeteer 的方案就能解决这些问题。

**Comment by ShinChven** [comment]
被puppeteer堵得要吐血了，求去掉依赖！

**Comment by ShinChven** [comment]
被puppeteer堵得要吐血了，求去掉依赖！
目前已从工程师删除ant design pro cli。
