### ISSUE TITLE
Learn from ng-cli

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-pro-cli#4]
https://github.com/angular/angular-cli/wiki/generate
https://github.com/angular/angular-cli/wiki/new

**Comment by yesmeck** [comment]
现在的 init 命令稍微有点反直觉。

先转发一个赞

<img width="754" alt="dingtalk20171103164723" src="https://user-images.githubusercontent.com/465125/32365931-f5af164c-c049-11e7-9714-e9c9922d8ff3.png">


<img width="419" alt="dingtalk20171103164839" src="https://user-images.githubusercontent.com/465125/32365924-f05cccfc-c049-11e7-8929-8d66c156b464.png">

一般感觉 init 是初始化当前目录（比如 git init），但是现在 init 的会新建一个目录，改成 `new` 或 `create` 更好点。

**Comment by yesmeck** [comment]
现在的 `new` 应该叫 `generate`。

**Comment by nikogu** [comment]
有道理

**Comment by yesmeck** [comment]
另外可以考虑下 yarn 的这个命令 https://yarnpkg.com/lang/en/docs/cli/create/

**Comment by bang88** [comment]
使用这个是不是就不用`CRA`了，另外生成的时候应该考虑一下支持用户自定义的模版生成代码。生成后的代码或许可以用`prettier`格式化一下，还有`TypeScript` version 😢 ,现在项目也有一个生成的，还是希望能够统一用一个脚手架就好

**Comment by nikogu** [comment]
这个下周重点优化下，上个 0.3.0 版本

- [ ] 名称优化，跟 `ng-cli` 保持一致，降低社区使用者思维转换
- [ ] 优化模板类型，结构
- [ ] 增加 `yarn` 支持 https://yarnpkg.com/lang/en/docs/cli/create/
- [ ] 支持自定义模板


- [ ] Typescript version `hold on`

**Comment by chenshuai2144** [comment]
typescript支持 我来搞一个把。我有一些样板代码
