### ISSUE TITLE
After creating a new project using `pro init`, run` npm install react-quill --save` in the project and install the unsuccessful other external modules.

### ISSUE THREAD

**Issue by fengyun2** [ant-design/ant-design-pro-cli#5]
After creating a new project using `pro init`, run` npm install react-quill --save` in the project and install the unsuccessful other external modules.

## Operating environment:

1. Windows10
2. node: v8.8.1
3. ant-design-pro-cli: v0.1.5

## Specific information is as follows:

```
npm ERR! path D:\test\js\1102\pro-demo\ant-design-pro\node_modules\ajv-keywordsnpm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall access
npm ERR! enoent ENOENT: no such file or directory, access 'D:\test\js\1102\pro-demo\ant-design-pro\node_modules\ajv-
keywords'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

**Comment by nikogu** [comment]
try https://github.com/visionmedia/debug/issues/261#issuecomment-207623445

**Comment by nikogu** [comment]
@fengyun2 try v0.2.2

**Comment by fengyun2** [comment]
@nikogu Upgrade to v0.2.2 , the command board directly stuck dead.

**Comment by nikogu** [comment]
@fengyun2 can you capture fully error message for me, i have no Windows environment.

**Comment by fengyun2** [comment]
![image](https://user-images.githubusercontent.com/8147202/32548650-5e9fec50-c4c1-11e7-86ec-f07a1b6c0e1e.png)
But I create a empty project with `npm init -y` and run `npm install react-quill --save` will success.

**Comment by nikogu** [comment]
i suggest you use [cnpm](https://npm.taobao.org/), by the way, what's error display?

**Comment by fengyun2** [comment]
Thank you. When use `cnpm`,  really installed successfully.
