### ISSUE TITLE
pro init is not working

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-pro-cli#6]
```
npm install ant-design-pro-cli -g
mkdir my-project && cd my-project
pro init
```

```
pro -V
0.2.0
```

---

There are `pro new` and `pro generate` with same function, are they duplicated?

**Comment by nikogu** [comment]
https://github.com/ant-design/ant-design-pro-cli#changelog

哈哈，我改了。。。0.2.0 =。-

**Comment by afc163** [comment]
<img width="475" alt="image" src="https://user-images.githubusercontent.com/507615/32439126-4aedd70c-c328-11e7-8fa2-d224aacf03dc.png">

pro new 好像不太对。

**Comment by nikogu** [comment]
@afc163 是的，我改挂了。。。

**Comment by afc163** [comment]
另外 pro 的 README 和文档要同步更新。否则会有人踩坑的。

https://github.com/ant-design/ant-design/issues/8121
https://github.com/ant-design/ant-design/issues/8120

**Comment by nikogu** [comment]
好的。。。

**Comment by mah93** [comment]
我还以为我环境有问题。。

**Comment by zhiphe** [comment]
我还以为我连Readme都读不懂了

**Comment by xyezir** [comment]
坑爹啊

**Comment by nikogu** [comment]
各位不好意思，家里环境有问题，npm 一直 publish 不上去，可以先用 0.1.5 版本，功能是一样的，就是改了命令的名字。。。。

- 0.1.5
    - init -> 初始化(new)  
    - new -> 创建模板(generator)
- 0.2.0
    - new -> 初始化
    - generator -> 创建模板

**Comment by nikogu** [comment]
done
