### ISSUE TITLE
pro new 三个选项是什么意思

### ISSUE THREAD

**Issue by lcoder** [ant-design/ant-design-pro-cli#9]
RT：
- standard

- simple

- browser history simple

这些什么用的，有什么区别吗？

**Comment by lcoder** [comment]
![image](https://user-images.githubusercontent.com/5225853/33001657-27fcaa58-cdea-11e7-94ac-70b51ea91ef7.png)
问下，`witch directory do you want to init to ?`中`witch`是不是想表达哪一个的意识？

**Comment by nikogu** [comment]
写错了。。。我改

**Comment by nikogu** [comment]
https://github.com/ant-design/ant-design-pro-cli#023

我到时候加简介到命令提示后面好了

**Comment by lcoder** [comment]
嗯嗯，还是加简介里好。

**Comment by nikogu** [comment]
https://github.com/ant-design/ant-design-pro-cli/blob/master/lib/new.js#L42
