### ISSUE TITLE
如何在保留国际化特性的情况下移除一个语言

### ISSUE THREAD

**Issue by lddhappy** [ant-design/ant-design-pro-cli#94]
现有i18n-remove直接移除了国际化支持，请问如何在保留国际化的情况下移除一个内置语言呢？
比如ant design pro v4版本内置了 zh-CN,zh-TW,en-US,pt-BR，如何移除pt-BR呢

**Comment by chenshuai2144** [comment]
现在不支持的，只支持全部删除
